-- AlterTable
ALTER TABLE "Page" ADD COLUMN IF NOT EXISTS "summary" TEXT;
ALTER TABLE "Page" ADD COLUMN IF NOT EXISTS "seoTitle" TEXT;
ALTER TABLE "Page" ADD COLUMN IF NOT EXISTS "seoDescription" TEXT;
